// Commercial banks + widely used microfinance/digital banks operating in Nigeria —
// used to populate the bank name picker when recording a manual bank transfer payment.
export const NIGERIAN_BANKS: string[] = [
'Access Bank',
'Citibank Nigeria',
'Ecobank Nigeria',
'Fidelity Bank',
'First Bank of Nigeria',
'First City Monument Bank (FCMB)',
'Globus Bank',
'Guaranty Trust Bank (GTBank)',
'Heritage Bank',
'Jaiz Bank',
'Keystone Bank',
'Optimus Bank',
'Parallex Bank',
'Polaris Bank',
'Premium Trust Bank',
'Providus Bank',
'Signature Bank',
'Stanbic IBTC Bank',
'Standard Chartered Bank',
'Sterling Bank',
'SunTrust Bank',
'Titan Trust Bank',
'Union Bank of Nigeria',
'United Bank for Africa (UBA)',
'Unity Bank',
'Wema Bank',
'Zenith Bank',
'Kuda Bank',
'Moniepoint MFB',
'Opay (Paycom)',
'PalmPay',
'VFD Microfinance Bank',
'Carbon',
'Rubies Bank',
'Sparkle Microfinance Bank'].
sort((a, b) => a.localeCompare(b));
